/*
Creator: Brandon Hahn
Description: This file was auto generated by creating a console application with 'dotnet new console' in a blank folder
*/


using System; //allows for the Console write

/*Namespaces group different classes together*/
namespace cpts_451_app_folder
{
    // OBJECTS are instances of CLASSES when the program runs.
    //Classes are bluprints that describe actions
    class Program
    {

        private static string myText = "jello vorld"; // example of a variable
        private static string changeInMethod;


        static void Main(string[] args) //main is a method
        {

            changeInMethod = "This string was created inside the method.";
            DisplayValue myDisplay = new DisplayValue(); //instatiate a new object of this class
            myDisplay.DisplayMessage(myText); //access the method
            myDisplay.DisplayMessage(changeInMethod);
        }
    }

    public class DisplayValue
    {
        public void DisplayMessage(string myMessage)
        {
            Console.WriteLine(myMessage);
        }
    }
}
