/*
Creator: Brandon Hahn
Description: This file was auto generated by creating a console application with 'dotnet new console' in a blank folder
*/


using System; //allows for the Console write

/*Namespaces group different classes together*/
namespace cpts_451_app_folder
{
    // OBJECTS are instances of CLASSES when the program runs
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
